x = input("Digite algo : ")
print("Eh alfabetico ?", x.isalpha())
print("Eh Numerico?", x.isnumeric())
print("Eh alfabeitico ou numerico?", x.isalnum())
print("Eh um digito?", x.isdigit())
print("Eh decimal?", x.isdecimal())
print("Eh minusculo?", x.islower())
print("Eh maiusculo?", x.isupper())
print("Eh identificador?", x.isidentifier())
print("Eh da tabela ascii?", x.isascii())
